UPDATE imageupload SET uploaddatatime = DATE_ADD(CURRENT_DATE, INTERVAL 1 YEAR) WHERE uploadDateTime < DATE_SUB(CURRENT_DATE, INTERVAL 7 DAY); 
DELETE FROM imageupload
WHERE uploadDateTime < DATE_SUB(CURRENT_DATE, INTERVAL 7 DAY);
